name: Release
on:
  release:
    types:
      - created
  push:
    branch:
      - master
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 50

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2       
    - uses: actions/setup-node@master
      with:
        node-version: 20
    - name: install dependencies
      run: yarn install
    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: yarn run publish
